### ISSUE TITLE
Design Protocol Relay

### ISSUE THREAD

**Issue by dhschall** [ease-lab/vSwarm#104]
**Problem: Support different procols in function**
In order to work together with all the testing framework all functions need to implement the _helloworld_ protocol.
This is first of all not nice, makes it harder to integrate new and different kind of functions.
Furthermore it has the large drawback that it limits the input and often functions can span different functionality depending on the functions input. 

**Describe the solution you'd like**
What we need is a protocol relay that:

1. Translate a helloworld request to any kind of protocol that we can choose
2. Generate different kind of input patterns we can also choose.

**Translation**
One need to implement a helloworld server that get triggered by a sayhello request.
After this trigger a input for the downstream protocol is generated and forwarded.
To generate this server one can start with my [this](https://github.com/ease-lab/serverless-perf/tree/develop/go-helper-lib/protos) and the grpcclient implementation. It creates an base interface for any kind of protocol. With the getGrpc client one can select which client function we want to implement.

For the server we want an input flag `-p, -proto` with which one can select which protol client to implement 

**Input generation**
We want different parameters to generate input values

1. Type (single, linear, random (with fixed seed))
2. Max number of inputs (n)
3. Range 
With that one can for example generate n=20 random numbers from 20-100 for the fibonacci function

Note the relay should be very fast to not limit ourself in the future therefore use golang and a static instantiation of the downstream protocol

In addition to do:

- [x] Create container
- [x] Makefile 
  - [x] Build all protocols
  - [x] Build realay container 
- [ ] Support tracing that we know the replay overhead
- [x] CI pipeline

**Comment by harshitgarg22** [comment]
Should we close this now?
