### ISSUE TITLE
Update invoker helloworld.proto to invoker.proto and rename functions

### ISSUE THREAD

**Issue by harshitgarg22** [ease-lab/vSwarm#119]
**Describe the bug**
Currently the proto file of invoker is based off the helloworld.proto specs, which is not ideal since it
1. Creates confusion when using functions like AES (which have helloworld.proto coincidentally but need not necessarily be limited to that, indeed standalone functions like online shopping won't be using that). 
2. Limits invoker to SayHello messages, which is not a good naming for it.

This will especially be true after relay is added to vSwarm, because how invoker speaks to relay and how relay speaks to AES (and other standalone functions)  will be different.

**Expected behavior**
A different proto structure for invoker (and subsequently other standalone functions).

My question is, will this end up breaking other functions in vSwarm? How much refactoring would be needed to change this?

**Comment by ustiugov** [comment]
So what do you propose? The only fundamental goal is to have the same protocol to trigger all benchmarks

**Comment by harshitgarg22** [comment]
Something like this would be ideal

```
syntax = "proto3";

option go_package = "github.com/ease-lab/vSwarm/tools/invoker/proto";

package invoker;

service Invoke {
  rpc InvokeRelay (InvokeRequest) returns (RelayResponse) {}
}

message InvokeRequest {
  string function_name = 1; // So relay can compare and check if the intended function is invoked?
  int rps = 2; // So relay can perhaps make the invokation run x number of times instead of constant pinging by invoker?
  int runDuration = 3; 
}

message RelayResponse {
  string message = 1;
}
```

This is a rough idea, relay can just as well use the current hello world system too. But this way would be more descriptive. My question is will this involve a lot of refactoring in existing functions to not be worth it?

**Comment by ustiugov** [comment]
renaming on its own does not add much value. Proto files are legacy preserving so adding new fields is harmless as long as they have unique IDs in the messages.
