### ISSUE TITLE
Istio spans unordered

### ISSUE THREAD

**Issue by cvetkovic** [ease-lab/vSwarm#239]
Hi people,

We were using Zipkin to trace down requests in vHive. However, we get some wired results where the Istio span (top-most span) finishes before the function execution completes (bottom-most spans). This is the case in around 40% of the traces we have, the rest are fine. Istio and activator are running on one node, and the queue-proxy pod is running on another node. If clocks on these two machines were not synchronized why the rest of the traces don't have this issue.

Any ideas on how we interpret these traces or we should discard them?

Thanks,
Lazar

![Screenshot from 2022-08-08 15-57-11](https://user-images.githubusercontent.com/16463659/183435906-037b2386-8d64-446e-b5f1-5a342c2c6f41.png)
?

**Comment by shyamjesal** [comment]
I don't know why is this happening. Posting on istio related forums might help.

**Comment by cvetkovic** [comment]
Ok. Thanks.
