### ISSUE TITLE
Auth knative throws RevisionMissing error when setting up revision

### ISSUE THREAD

**Issue by harshitgarg22** [ease-lab/vSwarm#45]
**Describe the bug**
In branch `standalone-functions`, when you run `auth-python` on knative using `harshitgarg22/auth-python` docker image, it doesn't run and `kn service list` gives you a `RevisionMissing` error. Invoker can reach the URL which means the route creates successfully but empty rps latency output means it isn't invoking.

**To Reproduce**
1. Checkout to `standalone-functions`
2. `cd benchmarks/auth`
3. `kn service apply -f ./knative_yamls/auth-python.yaml`
4. `kn service list`
5. `../../tools/invoker -port 50061 -dbg -time 10 -rps 1`

**Expected behavior**
It should run and invoker should return a non-empty rps latency file.

**Logs**
`kubectl get revision auth-python-00001 -output yaml` gives:

```
apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  annotations:
    serving.knative.dev/creator: kubernetes-admin
    serving.knative.dev/routingStateModified: "2022-02-08T07:10:29Z"
  creationTimestamp: "2022-02-07T20:03:24Z"
  generation: 1
  labels:
    serving.knative.dev/configuration: auth-python
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: a97362fb-b6ee-4a13-838c-125cf2d5a0a3
    serving.knative.dev/routingState: reserve
    serving.knative.dev/service: auth-python
    serving.knative.dev/serviceUID: a48bc9b0-b43a-4483-b283-1c25c70d4d94
  managedFields:
  - apiVersion: serving.knative.dev/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:serving.knative.dev/creator: {}
          f:serving.knative.dev/routingStateModified: {}
        f:labels:
          .: {}
          f:serving.knative.dev/configuration: {}
          f:serving.knative.dev/configurationGeneration: {}
          f:serving.knative.dev/configurationUID: {}
          f:serving.knative.dev/routingState: {}
          f:serving.knative.dev/service: {}
          f:serving.knative.dev/serviceUID: {}
        f:ownerReferences: {}
      f:spec:
        .: {}
        f:containerConcurrency: {}
        f:containers: {}
        f:enableServiceLinks: {}
        f:timeoutSeconds: {}
      f:status:
        .: {}
        f:actualReplicas: {}
        f:conditions: {}
        f:containerStatuses: {}
        f:observedGeneration: {}
    manager: controller
    operation: Update
    time: "2022-02-08T07:10:29Z"
  name: auth-python-00001
  namespace: default
  ownerReferences:
  - apiVersion: serving.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Configuration
    name: auth-python
    uid: a97362fb-b6ee-4a13-838c-125cf2d5a0a3
  resourceVersion: "6379410"
  uid: e5ea28c1-a885-4e4f-a025-af99115ca7d0
spec:
  containerConcurrency: 0
  containers:
  - image: docker.io/harshitgarg22/auth-python:latest
    imagePullPolicy: Always
    name: user-container
    ports:
    - containerPort: 50061
      name: h2c
      protocol: TCP
    readinessProbe:
      successThreshold: 1
      tcpSocket:
        port: 0
    resources: {}
  enableServiceLinks: false
  timeoutSeconds: 300
status:
  actualReplicas: 0
  conditions:
  - lastTransitionTime: "2022-02-07T20:13:56Z"
    message: The target is not receiving traffic.
    reason: NoTraffic
    severity: Info
    status: "False"
    type: Active
  - lastTransitionTime: "2022-02-07T20:13:26Z"
    message: |
      Container failed with: Traceback (most recent call last):
        File "/app/server.py", line 13, in <module>
          import helloworld_pb2
      ModuleNotFoundError: No module named 'helloworld_pb2'
    reason: ExitCode1
    status: "False"
    type: ContainerHealthy
  - lastTransitionTime: "2022-02-07T20:13:56Z"
    message: Initial scale was never achieved
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-02-07T20:13:56Z"
    message: Initial scale was never achieved
    reason: ProgressDeadlineExceeded
    status: "False"
    type: ResourcesAvailable
  containerStatuses:
  - imageDigest: index.docker.io/harshitgarg22/auth-python@sha256:a2b7e9b0a84f36010374f17d6bdfd5930ded29352863260d67a8574ce4b45203
    name: user-container
  observedGeneration: 1
```

**Notes**
Interestingly, I get this error
```
  - lastTransitionTime: "2022-02-07T20:13:26Z"
    message: |
      Container failed with: Traceback (most recent call last):
        File "/app/server.py", line 13, in <module>
          import helloworld_pb2
      ModuleNotFoundError: No module named 'helloworld_pb2'
```

But I did not get this error when I ran it locally using `docker-compose -f ./compose_yamls/docker-compose-auth-python.yaml up`. I have added `COPY ./proto/* /app/` in `Dockerfile.python`, so I expected it to run with knative also.

**Comment by ustiugov** [comment]
Your logs (the section called **Logs** do not contain the error message. Is the error that you observe is as follows?
>       Container failed with: Traceback (most recent call last):
        File "/app/server.py", line 13, in <module>
          import helloworld_pb2
      ModuleNotFoundError: No module named 'helloworld_pb2'

if so, it must be reproducible with docker compose, it has nothing to do with Knative. Please double check if you run the same docker image.

**Comment by harshitgarg22** [comment]
> Your logs (the section called **Logs** do not contain the error message. Is the error that you observe is as follows?
> 
So the first error is 
```
auth-python   http://auth-python.default.192.168.1.240.sslip.io                      10m     0 OK / 3     False   RevisionMissing : Configuration "auth-python" does not have any ready Revision.
```
which does not give a lot of info. Hence I ran `kubectl get revision auth-python-00001 --output yaml` to give me the above mentioned output, for some more info about what's going on.

> ```
>     File "/app/server.py", line 13, in <module>
>       import helloworld_pb2
>   ModuleNotFoundError: No module named 'helloworld_pb2'
> ```
> 
> if so, it must be reproducible with docker compose, it has nothing to do with Knative. Please double check if you run the same docker image.

I did that again (build, push, pull), but it still didn't work.

I actually checked the port number in knative configuration, and that was incorrect. So now the knative service sets up properly but the invoker isn't giving results like the local docker build does, so it's half-solved for now.

**Comment by ustiugov** [comment]
please get to the bottom of the ` ModuleNotFoundError: No module named 'helloworld_pb2'` problem, some of your assumptions do not stand. instead of docker-compose you can just use docker interactively and inspect the files, etc. Also, k8s allows to access the shell of a running container, you can attach to it interactively and check. If you cannot find how to do it online, please let me know.

**Comment by ustiugov** [comment]
also, I wonder if `kn service apply -f ./knative_yamls/auth-python.yaml` returns an error.
