### ISSUE TITLE
Upgrade otel

### ISSUE THREAD

**Issue by dhschall** [ease-lab/vSwarm#92]
We need to upgrade the otel module for tracing from v0.20.0 => v1.4.1

I updated all vhive dependencies from vhive to vSwarm. When I want to update the mod file for the invoker I get the following error.
![image](https://user-images.githubusercontent.com/31178749/158447688-02325427-9342-479d-bf4d-34df5108a59a.png)

Right now it works because the require points still to the vhive repo but to make this clean we want to update this

**Comment by ustiugov** [comment]
@MBaczun @shyamjesal guys what do you think?

**Comment by shyamjesal** [comment]
This was a bug in the library and if i remember correctly, @MBaczun solved it by using the old version.

**Comment by MBaczun** [comment]
That's right, unfortunately I never found a fix other than just using an older version :( . Check out https://github.com/ease-lab/vhive/issues/315.
I opened an issue with the opentelemetry guys too but they weren't able to replicate the problem if I remember right.

**Comment by ustiugov** [comment]
thanks! @dhschall can you write an update on the upstream issue (mentioned in 315), specifying how to reproduce this. Ideally, provide them with a simple test in a docket container that they can run.

**Comment by harshitgarg22** [comment]
I encountered this error myself while adding relay and found that if we upgrade the version to v0.31.0 (latest), it uses the correct semconv package. Multiple issues happen (with semconv, and otherwise when upgrading otelgrpc) with other packages like zipkin also where the upstream has decided to change the name of functions (or remove them entirely) in the newer versions and the code had to be changed accordingly.

**Comment by ustiugov** [comment]
@harshitgarg22 That's great, please submit a fix

**Comment by harshitgarg22** [comment]
They are spread about in https://github.com/ease-lab/vSwarm/tree/add-relay. I will try to set it up for mergeability very soon. (It's better this way than to try to make a separate branch+PR).

**Comment by ustiugov** [comment]
ok

**Comment by harshitgarg22** [comment]
Yes we use v0.31.0 now
